# Generated by Django 3.0.5 on 2020-12-20 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201220_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 14, 13, 41, 230695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field=600, upload_to='blog/images/', width_field=1000),
        ),
    ]
